import { NextRequest, NextResponse } from "next/server";

/**
 * GET /api/hu/candidate/[id]
 *
 * Returns intelligence data for a candidate by NVI kpn_id.
 *
 * Data source: scored-candidates.json (bundled at build time).
 * This file is regenerated by scripts/merge_intelligence.py and committed
 * to the repo — Vercel redeploys automatically on push to main.
 *
 * Why static bundling instead of runtime filesystem reads:
 * Vercel serverless functions don't have access to the repo's data/ directory
 * at runtime. Bundling via import() is the correct pattern for Next.js.
 *
 * Update cadence: daily after NVI refresh (17:10 GMT) + scraper runs.
 */

// Dynamic import so the file is bundled by Next.js
// Next.js will trace this import and include the JSON in the deployment
import scoredData from "../../../../../data/hungary/scored-candidates.json";

type EvidenceItem = {
  source: string;
  weight: string;
  type: string;
  title?: string;
  url?: string;
  date?: string;
  excerpt?: string;
  text?: string;
  note?: string;
  confidence?: string;
  tags?: string[];
};

type ScoredCandidate = {
  kpn_id: number;
  name: string;
  party: string;
  party_id: string | null;
  sources_checked: string[];
  sources_with_data: string[];
  evidence: EvidenceItem[];
  scores: Record<string, unknown>;
  flags: unknown[];
  total_evidence_items: number;
  data_quality: "rich" | "some" | "none";
  last_updated: string;
};

type ScoredData = {
  meta: {
    generated_at: string;
    total_candidates: number;
    stats: Record<string, number>;
    sources_checked: string[];
  };
  candidates: ScoredCandidate[];
};

// Source display metadata — weight and label for the UI
const SOURCE_META: Record<string, { label: string; weight: "high" | "medium" | "low" }> = {
  "atlatszo.hu":     { label: "Átlátszó",          weight: "high"   },
  "hvg.hu":          { label: "HVG",                weight: "medium" },
  "telex.hu":        { label: "Telex",              weight: "medium" },
  "444.hu":          { label: "444",                weight: "medium" },
  "parlament.hu":    { label: "Parliament",         weight: "high"   },
  "e-cegjegyzek.hu": { label: "Business Registry",  weight: "medium" },
  "ekr.gov.hu":      { label: "Procurement (EKR)",  weight: "high"   },
};

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const kpnId = parseInt(id, 10);

  if (isNaN(kpnId)) {
    return NextResponse.json({ error: "Invalid candidate id" }, { status: 400 });
  }

  const data = scoredData as ScoredData;
  const candidate = data.candidates.find((c) => c.kpn_id === kpnId);

  if (!candidate) {
    return NextResponse.json({ error: "Candidate not found" }, { status: 404 });
  }

  if (candidate.total_evidence_items === 0) {
    return NextResponse.json({ error: "No intelligence data found" }, { status: 404 });
  }

  // Group evidence by source, attach display metadata
  const sourceGroups: Record<string, {
    label: string;
    weight: "high" | "medium" | "low";
    item_count: number;
    items: EvidenceItem[];
  }> = {};

  for (const item of candidate.evidence) {
    const src = item.source;
    if (!sourceGroups[src]) {
      const meta = SOURCE_META[src] ?? { label: src, weight: "low" as const };
      sourceGroups[src] = { ...meta, item_count: 0, items: [] };
    }
    if (sourceGroups[src].items.length < 20) {
      sourceGroups[src].items.push(item);
    }
    sourceGroups[src].item_count++;
  }

  return NextResponse.json({
    kpn_id: kpnId,
    name: candidate.name,
    party: candidate.party,
    data_quality: candidate.data_quality,
    sources_checked: candidate.sources_checked,
    scores: candidate.scores,
    flags: candidate.flags,
    sources: sourceGroups,
    generated_at: data.meta.generated_at,
    last_updated: candidate.last_updated,
  });
}
