FROM python:3.12-slim

WORKDIR /app

COPY . /app

RUN python -m pip install --upgrade pip \
    && python -m pip install -e . \
    && chmod +x /app/docker/local-entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/app/docker/local-entrypoint.sh"]

