/**
 * GET /api/hu/feed
 *
 * Returns a curated news feed for the Hungary pilot.
 * Merges domestic media (from scored-candidates.json evidence),
 * foreign press (from foreign/feed.json), and social signals.
 *
 * Query params:
 *   ?topic=elections|rule_of_law|economy|eu_relations|ukraine_russia|migration|politics
 *   ?lang=en|hu|all   (default: all)
 *   ?type=press|foreign|social|all  (default: press,foreign)
 *   ?limit=20         (default: 20, max: 50)
 *
 * Data is bundled at build time from the data/ directory.
 * Regenerated by scraper runs and committed to main → auto-deploys to Vercel.
 */

import { NextRequest, NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

// Topic taxonomy (matches scraper output)
const TOPIC_SECTIONS = [
  { id: 'elections',    label_en: 'Elections & Campaigns', label_hu: 'Választás és kampány',  emoji: '🗳️' },
  { id: 'rule_of_law',  label_en: 'Rule of Law',           label_hu: 'Jogállamiság',           emoji: '⚖️' },
  { id: 'economy',      label_en: 'Economy',               label_hu: 'Gazdaság',               emoji: '💰' },
  { id: 'eu_relations', label_en: 'EU & Foreign Affairs',  label_hu: 'EU és külpolitika',      emoji: '🌍' },
  { id: 'ukraine_russia', label_en: 'Ukraine / Russia',    label_hu: 'Ukrajna / Oroszország',  emoji: '🕊️' },
  { id: 'politics',     label_en: 'Politics',              label_hu: 'Belpolitika',             emoji: '🏛️' },
  { id: 'migration',    label_en: 'Migration',             label_hu: 'Migráció',               emoji: '🌐' },
  { id: 'corruption',   label_en: 'Corruption & Accountability', label_hu: 'Korrupció és átláthatóság', emoji: '🔍' },
];

// Curated fallback feed (static — shown when no scraped data exists yet)
const CURATED_FALLBACK = [
  {
    id: 'fallback_001',
    title: 'Hungary 2026 parliamentary election — what you need to know',
    snippet: 'On April 12, Hungarians go to the polls in one of the most closely watched elections in Central Europe. Prism is tracking 666 candidates across 106 constituencies.',
    url: 'https://github.com/Prism-civic/prism/blob/main/docs/HUNGARY_PILOT_PLAN.md',
    source_name: 'Prism Civic Intelligence',
    source_domain: 'prism-sooty-chi.vercel.app',
    weight: 'high',
    language: 'en',
    source_country: 'EU',
    topic: 'elections',
    content_type: 'press',
    published: new Date().toISOString(),
    fetched_at: new Date().toISOString(),
    is_curated: true,
  },
  {
    id: 'fallback_002',
    title: 'RFE/RL: Hungary election coverage',
    snippet: 'Radio Free Europe / RFE-RL covers the Hungarian parliamentary election and the political landscape ahead of April 12.',
    url: 'https://www.rferl.org/z/631',
    source_name: 'Radio Free Europe / RFE-RL',
    source_domain: 'rferl.org',
    weight: 'high',
    language: 'en',
    source_country: 'US',
    topic: 'elections',
    content_type: 'press',
    published: new Date().toISOString(),
    fetched_at: new Date().toISOString(),
    is_curated: true,
  },
  {
    id: 'fallback_003',
    title: 'Guardian: Hungary under Orbán',
    snippet: 'The Guardian\'s coverage of Hungarian politics, rule of law, and the 2026 elections.',
    url: 'https://www.theguardian.com/world/hungary',
    source_name: 'The Guardian',
    source_domain: 'theguardian.com',
    weight: 'medium',
    language: 'en',
    source_country: 'UK',
    topic: 'rule_of_law',
    content_type: 'press',
    published: new Date().toISOString(),
    fetched_at: new Date().toISOString(),
    is_curated: true,
  },
  {
    id: 'fallback_004',
    title: 'Politico: Central Europe politics briefing',
    snippet: 'Politico Europe\'s ongoing coverage of Hungarian political developments, EU relations, and the rule of law situation.',
    url: 'https://www.politico.eu/europe-poll-of-polls/hungary/',
    source_name: 'Politico Europe',
    source_domain: 'politico.eu',
    weight: 'high',
    language: 'en',
    source_country: 'EU',
    topic: 'eu_relations',
    content_type: 'press',
    published: new Date().toISOString(),
    fetched_at: new Date().toISOString(),
    is_curated: true,
  },
  {
    id: 'fallback_005',
    title: 'Átlátszó: Korrupciós ügyek és átláthatóság',
    snippet: 'Az Átlátszó korrupció-ellenes nyomozó újságírás. Nyomon követik a közpénzek felhasználását és a jelöltek érdekeltségeit.',
    url: 'https://atlatszo.hu',
    source_name: 'Átlátszó',
    source_domain: 'atlatszo.hu',
    weight: 'high',
    language: 'hu',
    source_country: 'HU',
    topic: 'corruption',
    content_type: 'press',
    published: new Date().toISOString(),
    fetched_at: new Date().toISOString(),
    is_curated: true,
  },
  {
    id: 'fallback_006',
    title: 'r/hungary — public discussion on the 2026 elections',
    snippet: 'English-language community discussion about Hungarian politics, the election, and daily life in Hungary.',
    url: 'https://reddit.com/r/hungary',
    source_name: 'Reddit r/hungary',
    source_domain: 'reddit.com',
    weight: 'low',
    language: 'en',
    source_country: 'US',
    topic: 'elections',
    content_type: 'social',
    is_sentiment: true,
    published: new Date().toISOString(),
    fetched_at: new Date().toISOString(),
    is_curated: true,
  },
];

// Try to load scraped feed data via fs (server-side only, safe in Next.js API routes)
async function loadScrapedFeed(): Promise<Record<string, unknown>[]> {
  try {
    const fs   = await import('fs');
    const path = await import('path');

    const root        = path.resolve(process.cwd(), '..', 'data', 'hungary', 'intelligence');
    const foreignPath = path.join(root, 'foreign', 'feed.json');
    const socialPath  = path.join(root, 'social',  'feed.json');

    const readJson = (p: string): Record<string, unknown>[] => {
      try {
        const raw = fs.readFileSync(p, 'utf-8');
        const parsed = JSON.parse(raw);
        return Array.isArray(parsed.items) ? parsed.items : [];
      } catch { return []; }
    };

    return [...readJson(foreignPath), ...readJson(socialPath)];
  } catch {
    return [];
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const topic  = searchParams.get('topic') ?? 'all';
  const lang   = searchParams.get('lang') ?? 'all';
  const type   = searchParams.get('type') ?? 'all';
  const limit  = Math.min(parseInt(searchParams.get('limit') ?? '20'), 50);

  let items = await loadScrapedFeed();

  // Fall back to curated items if no scraped data yet
  if (items.length === 0) {
    items = CURATED_FALLBACK as Record<string, unknown>[];
  } else {
    // Prepend curated to fill any gaps
    const curated = CURATED_FALLBACK.map(c => ({ ...c, is_curated: true }));
    items = [...curated, ...items];
  }

  // Deduplicate by url
  const seen = new Set<string>();
  items = items.filter(item => {
    const url = item.url as string;
    if (!url || seen.has(url)) return false;
    seen.add(url);
    return true;
  });

  // Filter
  if (topic !== 'all') {
    items = items.filter(i => i.topic === topic);
  }
  if (lang !== 'all') {
    items = items.filter(i => i.language === lang);
  }
  if (type !== 'all') {
    items = items.filter(i => i.content_type === type || (type === 'social' && (i as Record<string, unknown>).is_sentiment));
  }

  // Sort: high-weight press first, then by recency
  const weightOrder = { high: 0, medium: 1, low: 2 };
  items.sort((a, b) => {
    const wa = weightOrder[a.weight as keyof typeof weightOrder] ?? 2;
    const wb = weightOrder[b.weight as keyof typeof weightOrder] ?? 2;
    if (wa !== wb) return wa - wb;
    return (b.fetched_at as string ?? '').localeCompare(a.fetched_at as string ?? '');
  });

  return NextResponse.json({
    items: items.slice(0, limit),
    total: items.length,
    sections: TOPIC_SECTIONS,
    generated_at: new Date().toISOString(),
  });
}
